export interface IPackage {
  trackingNumber: String,
  senderName: String,
  senderPostalCode: String,
  senderCity:String,
  senderAddress:String,
  senderTelephone:Number,
  senderEmail:String,
  receiverName: String,
  receiverPostalCode:String,
  receiverCity:String,
  receiverAddress:String,
  receiverTelephone:Number,
  receiverEmail:String,
  packageDescription:String,
  packageWeight:Number,
  packageWidth:Number,
  packageLength:Number,
  packageHeight:Number,
}
